### PR TITLE
Updated Inventory and Player class with unit tests

### PR DESCRIPTION
**Pull request by hsuj**
Added new empty methods along with unit tests to check if there are no more pieces of a certain type or the entire inventory. Rearranged array initializations in Inventory. Removed testing specific methods which grabbed an index in the array to see if it was the appropriate Piece object in Inventory. Added tests to Player class to verify Inventory object worked.

### CODE REVIEW

**Comment by gonzalonunez** [comment]
Yo @hsuj. This is what I did in `Deck.java`:
```java
public Tile drawTile() throws ArrayIndexOutOfBoundsException {
        if (gameDeck.isEmpty()) {
            throw new ArrayIndexOutOfBoundsException("No more tiles remaining in the Deck");
        }
        return gameDeck.remove(0);
    }
```
Do you think something like this makes sense for this case as well?

**Comment by gonzalonunez** [comment]
This looks great to me. Should allow us to easily implement a lot of functionality. Can you address the conflicts in `CreateSettlementSteps.java`?

**Comment by hsuj** [comment]
I'm unable to click the Resolve conflicts button so I can't tell exactly what is conflicting in that file. The only thing I changed as far as I can see is adding the playerID parameter when creating the Player object.

**Comment by gonzalonunez** [comment]
Ok, you'll have to do it yourself via the command line. Go to your branch and:

1. `git fetch upstream`
2. `git rebase upstream/master`

It's gonna say you have some conflicts. You'll go into IntelliJ and make the file looks like how you want it to. Once you make the file look all good, you'll **make sure the project builds and all the tests pass.**

Then:

1. `git add .`
2. `git rebase --continue`

Repeat this process until you rebase successfully. Then you should be able to push up. If it doesn't let you push up, let me know. You *might* have to force push but I'll tell you how to do that if it tells you that you need to.

**Pull request merged**
